INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
	('cannabis', 'Cannabis', 1, 0, 1),
	('marijuana', 'Marijuana', 1, 0, 1),
	('coca', 'CocaPlant', 1, 0, 1),
	('cocaine', 'Coke', 1, 0, 1),
	('ephedra', 'Ephedra', 1, 0, 1),
	('ephedrine', 'Ephedrine', 1, 0, 1),
	('poppy', 'Poppy', 1, 0, 1),
	('opium', 'Opium', 1, 0, 1),
	('meth', 'Meth', 1, 0, 1),
	('heroine', 'Heroine', 1, 0, 1),
	('beer', 'Beer', 1, 0, 1),
	('tequila', 'Tequila', 1, 0, 1),
	('vodka', 'Vodka', 1, 0, 1),
	('whiskey', 'Whiskey', 1, 0, 1),
	('crack', 'Crack', 1, 0, 1),
	('drugtest', 'DrugTest', 1, 0, 1),
	('breathalyzer', 'Breathalyzer', 1, 0, 1),
	('fakepee', 'Fake Pee', 1, 0, 1),
	('pcp', 'PCP', 1, 0, 1),
	('dabs', 'Dabs', 1, 0, 1),
	('painkiller', 'Painkiller', 1, 0, 1),
	('narcan', 'Narcan', 1, 0, 1)
;
